version: '1'
services:
  h2:
    container_name: 'h2'
    hostname: 'h2'
    image: h2non/imaginary
    ports:
      - "8181:8181"
      - "1521:1521"
    volumes:
      - h2-data:/opt/h2-data
volumes:
  h2-data:
